- src/main/docker/Dockerfile
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=485727
> US485727: Use jre11 base image

- release-notes-2.1.0.md
- src/main/docker/Dockerfile
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=628005
> US628005: Update Opensearch to 1.3.8

- release-notes-2.3.0.md
- src/main/docker/Dockerfile
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=738057
Tested in classification worker here: https://github.houston.softwaregrp.net/Verity/worker-classification/pull/214
> US738057: Updated OpenSearch to version 1.3.11

- release-notes-2.4.0.md
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=778002
> US778002: Release preparation

- pom.xml
- src/main/docker/Dockerfile
- src/main/docker/log4j2.properties
- src/main/docker/scripts/start.sh
- src/test/java/com/github/cafapi/opensuse/opensearch1/ContainerIT.java
- src/test/resources/simplelogger.properties
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=868108
> US868108: Update Copyright statements to 2024

- release-notes-2.6.0.md
- src/main/docker/Dockerfile
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=871037
> US871037: Updated OpenSearch to version 1.3.14

- release-notes-2.7.0.md
- src/main/docker/Dockerfile
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=890036
> US890036: Release preparation

- release-notes-2.8.0.md
- src/main/docker/Dockerfile
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=896108
> US896108: Updated OpenSearch to version 1.3.15

- src/main/docker/Dockerfile
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=898097
Created a multi-stage build, removed the packages in the builder stage and then created a new actual image section. Tested this image in the classification worker [here](https://github.houston.softwaregrp.net/Verity/worker-classification/pull/268) and all tests are passing.
> US898097: Rework build to remove packages from image

- release-notes-3.0.0.md
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=901083
> US901083: Release preparation

- src/main/docker/Dockerfile
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=895066
> US895066: Updated to latest java image release

- pom.xml
- release-notes-3.1.0.md
- src/main/docker/Dockerfile
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=915349
> I915349: Upgrade to OpenSearch 1.3.16

- pom.xml
- release-notes-3.1.0.md
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=914428
> I914428: Remove commons-text from exclusion

- release-notes-3.1.0.md
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=917104
> US917104: Release preparation

- pom.xml
- release-notes-3.2.0.md
- src/test/java/com/github/cafapi/opensuse/opensearch1/ContainerIT.java
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=914108
> US914108: Version Currency: JUnit 5 migration

- pom.xml
- release-notes-3.2.0.md
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=920085
> US920085: Release preparation

- README.md
- pom.xml
- release-notes-3.2.0.md
- src/main/docker/Dockerfile
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=929026
> US929026: Updated to run on Java 21

- pom.xml
- release-notes-3.3.8.md
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=1011076
> US1011076: Release preparation

- pom.xml
- release-notes-3.3.9.md
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=1019001
> US1019001: Release preparation

- pom.xml
- release-notes-3.3.11.md
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=1031054
> US1031054: Release preparation

- pom.xml
- release-notes-3.3.12.md
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=1041232
> US1041232: Release preparation

- pom.xml
- release-notes-3.3.13.md
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=1041236
> US1041236: Release preparation
